name: Linux Build

on:
  push: {}
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: provide toolchain
        run: |-
          sudo apt-get update
          sudo apt-get install mpc libmpfr-dev libgmp3-dev cmake ppl-dev
          sudo mkdir /usr/local/cross 
          sudo wget -q -P /usr/src/gcc https://ftp.gnu.org/gnu/gcc/gcc-13.2.0/gcc-13.2.0.tar.gz
          sudo wget -q -P /usr/src/binutils https://ftp.gnu.org/gnu/binutils/binutils-2.41.tar.gz
          echo "Extracting GCC"
          sudo tar -xsf /usr/src/gcc/gcc-13.2.0.tar.gz -C /usr/src/gcc
          echo "Extracting binutils"
          sudo tar -xsf /usr/src/binutils/binutils-2.41.tar.gz -C /usr/src/binutils

          cd /usr/src
          sudo mkdir build-binutils
          cd /usr/src/build-binutils
          sudo sh -c "../binutils/./configure --target=sh3eb-elf --prefix=/usr/local/cross --disable-nls"
          make
          sudo make install
          
          export PATH=$PATH:/usr/local/cross/bin
          cd /usr/src
          sudo mkdir build-gcc
          cd /usr/src/build-gcc
          sudo sh -c "../gcc/./configure --target=sh3eb-elf --prefix=/usr/local/cross --disable-nls --enable-languages=c,c++ --without-headers"
          make all-gcc
          sudo make install-gcc
          make all-target-libgcc
          sudo make install-target-libgcc

          cd /usr/src
          sudo mkdir build-mkg3a
          sudo wget -P /usr/src/build-mkg3a https://gitlab.com/taricorp/mkg3a/-/archive/master/mkg3a-master.tar.gz
          cd /usr/src/build-mkg3a
          cmake .
          make
          su -c "make install"

      - name: make
        run: make 

          

          

 
